-- Example DDL Output
-- This file shows what the generated DDL would look like for a sample schema

-- DDL for schema: myschema
-- Generated by PostgreSQL DDL Generator

-- Create schema if not exists
CREATE SCHEMA IF NOT EXISTS myschema;

-- ======================================
-- TRIGGER FUNCTIONS
-- ======================================

-- Function: myschema.update_modified_timestamp
CREATE OR REPLACE FUNCTION myschema.update_modified_timestamp()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
    NEW.modified_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$function$;

-- ======================================
-- SEQUENCES
-- ======================================

-- Sequence: myschema.custom_seq
CREATE SEQUENCE myschema.custom_seq
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    START WITH 1
    CACHE 1
    NO CYCLE;

-- ======================================
-- TABLES
-- ======================================

-- Table: myschema.users
CREATE TABLE myschema.users (
    user_id bigserial NOT NULL,
    username character varying(50) NOT NULL,
    email character varying(100) NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    modified_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    is_active boolean DEFAULT true NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (user_id),
    CONSTRAINT users_email_key UNIQUE (email),
    CONSTRAINT users_username_key UNIQUE (username),
    CONSTRAINT users_email_check CHECK ((length((email)::text) > 5))
);
COMMENT ON COLUMN myschema.users.user_id IS 'Primary key for users table';
COMMENT ON COLUMN myschema.users.email IS 'User email address, must be unique';
COMMENT ON TABLE myschema.users IS 'Stores user account information';

-- Table: myschema.profiles
CREATE TABLE myschema.profiles (
    profile_id bigserial NOT NULL,
    user_id bigint NOT NULL,
    first_name character varying(50),
    last_name character varying(50),
    bio text,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT profiles_pkey PRIMARY KEY (profile_id),
    CONSTRAINT profiles_user_id_key UNIQUE (user_id)
);

-- Table: myschema.posts
CREATE TABLE myschema.posts (
    post_id bigserial NOT NULL,
    user_id bigint NOT NULL,
    title character varying(200) NOT NULL,
    content text,
    status character varying(20) DEFAULT 'draft'::character varying,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    modified_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT posts_pkey PRIMARY KEY (post_id),
    CONSTRAINT posts_status_check CHECK (((status)::text = ANY ((ARRAY['draft'::character varying, 'published'::character varying, 'archived'::character varying])::text[])))
);

-- Table: myschema.comments
CREATE TABLE myschema.comments (
    comment_id bigserial NOT NULL,
    post_id bigint NOT NULL,
    user_id bigint NOT NULL,
    content text NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT comments_pkey PRIMARY KEY (comment_id)
);

-- ======================================
-- FOREIGN KEY CONSTRAINTS
-- ======================================

-- Foreign Key Constraints
ALTER TABLE myschema.profiles
    ADD CONSTRAINT profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES myschema.users(user_id) ON DELETE CASCADE;

ALTER TABLE myschema.posts
    ADD CONSTRAINT posts_user_id_fkey FOREIGN KEY (user_id) REFERENCES myschema.users(user_id) ON DELETE CASCADE;

ALTER TABLE myschema.comments
    ADD CONSTRAINT comments_post_id_fkey FOREIGN KEY (post_id) REFERENCES myschema.posts(post_id) ON DELETE CASCADE;

ALTER TABLE myschema.comments
    ADD CONSTRAINT comments_user_id_fkey FOREIGN KEY (user_id) REFERENCES myschema.users(user_id) ON DELETE CASCADE;

-- ======================================
-- INDEXES
-- ======================================

-- Index: myschema.idx_posts_user_id
CREATE INDEX idx_posts_user_id ON myschema.posts USING btree (user_id);

-- Index: myschema.idx_posts_status
CREATE INDEX idx_posts_status ON myschema.posts USING btree (status);

-- Index: myschema.idx_posts_created_at
CREATE INDEX idx_posts_created_at ON myschema.posts USING btree (created_at DESC);

-- Index: myschema.idx_comments_post_id
CREATE INDEX idx_comments_post_id ON myschema.comments USING btree (post_id);

-- Index: myschema.idx_comments_user_id
CREATE INDEX idx_comments_user_id ON myschema.comments USING btree (user_id);

-- ======================================
-- TRIGGERS
-- ======================================

-- Trigger: myschema.users_update_modified_timestamp
CREATE TRIGGER users_update_modified_timestamp BEFORE UPDATE ON myschema.users FOR EACH ROW EXECUTE FUNCTION myschema.update_modified_timestamp();

-- Trigger: myschema.posts_update_modified_timestamp
CREATE TRIGGER posts_update_modified_timestamp BEFORE UPDATE ON myschema.posts FOR EACH ROW EXECUTE FUNCTION myschema.update_modified_timestamp();

-- ======================================
-- VIEWS
-- ======================================

-- View: myschema.v_user_posts
CREATE OR REPLACE VIEW myschema.v_user_posts AS
SELECT 
    u.user_id,
    u.username,
    p.post_id,
    p.title,
    p.status,
    p.created_at
FROM myschema.users u
JOIN myschema.posts p ON u.user_id = p.user_id
WHERE p.status = 'published'::character varying;

-- View: myschema.v_post_stats
CREATE OR REPLACE VIEW myschema.v_post_stats AS
SELECT 
    p.post_id,
    p.title,
    p.user_id,
    COUNT(c.comment_id) AS comment_count,
    MAX(c.created_at) AS last_comment_at
FROM myschema.posts p
LEFT JOIN myschema.comments c ON p.post_id = c.post_id
GROUP BY p.post_id, p.title, p.user_id;
